name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          brew install ldid xz

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git theos
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/theos/bin" >> $GITHUB_PATH

      - name: Setup SDKs
        run: |
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip -d .
          mkdir -p theos/sdks
          mv sdks-master/*.sdk theos/sdks/
          rm -rf master.zip sdks-master

      - name: Build Package
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: StikJIT-Deb
          path: packages/*.deb

      - name: Upload .dylib Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: StikJIT-Dylib
          path: obj/*.dylib

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*.deb
          generate_release_notes: true