# .github/workflows/build.yml
name: Build Theos Tweak

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 1. Checkout your code
      - name: Check out repo
        uses: actions/checkout@v4

      # 2. Install Theos environment
      - name: Install Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: 'theos'
          theos-src: 'https://github.com/theos/theos'
          theos-sdks: 'https://github.com/theos/sdks'
          theos-sdks-branch: 'master'
          orion: 'false'

      # 3. Build the tweak
      - name: Build tweak
        run: |
          export THEOS=$(pwd)/theos
          export PATH="$THEOS/bin:$PATH"
          make clean package

      # 4. Upload .deb artifact
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: tweak-package
          path: ./packages/*.deb

      # 5. Upload .dylib artifact
      - name: Upload .dylib artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dylib
          path: ./obj/*.dylib